language: python
sudo: false
branches:
    only:
        - master
        - /^\d\.\d+$/

matrix:
  include:
    - python: 3.5


install:
    - pip install -U pip tox codecov

script:
    - pip install -e deep-deep
    - py.test --doctest-modules deep-deep/deepdeep

after_success:
    - codecov

cache:
    directories:
        - $HOME/.cache/pip
